name: random_color_solid
description: A Flutter application for random color generating. Solid. Ivan Bandura.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.3.10
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.5
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icons/appIcon.png"
  android: true
  ios: true

flutter:
  assets:
    - assets/fonts/
  uses-material-design:
    true
  fonts:
    - family:  Title
      fonts:
        - asset: assets/fonts/Title.ttf

flutter_intl:
  enabled: true

